### ISSUE TITLE
sci-fuzzy failing to installs

### ISSUE THREAD

**Issue by DavidNordin** [hassio-addons/app-appdaemon#321] opened 2024-01-04 22:00 UTC
# Problem/Motivation

> Trying to install sci-fuzzy

## Expected behavior

> Install sucess

## Actual behavior

> Failing on startup

## Steps to reproduce

> add sci-fuzzy as a python package

## Proposed changes

´
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting scikit-fuzzy
  Downloading scikit-fuzzy-0.4.2.tar.gz (993 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 994.0/994.0 kB 9.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.6.0 in /usr/lib/python3.11/site-packages (from scikit-fuzzy) (1.25.2)
Collecting scipy>=0.9.0 (from scikit-fuzzy)
  Downloading scipy-1.11.4.tar.gz (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 19.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      + meson setup /tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606 /tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606/.mesonpy-liscda_h -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606/.mesonpy-liscda_h/meson-python-native-file.ini
      The Meson build system
      Version: 1.3.1
      Source dir: /tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606
      Build dir: /tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606/.mesonpy-liscda_h
      Build type: native build
      Project name: SciPy
      Project version: 1.11.4
      
      ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"
      
      A full log can be found at /tmp/pip-install-8_xye6ah/scipy_587897c3d50243cf87c5c2c8f4525606/.mesonpy-liscda_h/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[22:57:24] FATAL: Failed installing package scikit-fuzzy
s6-rc: warning: unable to start service init-appdaemon: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
´

**Comment by frenck** [comment] 2024-01-05 09:04
As per log you posted:

```
  ../meson.build:1:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
  The following exception(s) were encountered:
  Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
  Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
  Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
  Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
  Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
  Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
  Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"
```

If you install packages that have dependencies to install, you need to install those dependencies too.

Closing this issue, as it is not a bug, but an configuration error.

../Frenck

**Closed as not planned by frenck** 2024-01-05 09:04 UTC
