### ISSUE TITLE
Appdeamon config folder is "cleared"", therefore appdaemon isn't starting

### ISSUE THREAD

**Issue by mplogas** [hassio-addons/app-appdaemon#293] opened 2023-11-15 12:50 UTC
# Problem/Motivation
```
Add-on version: 0.15.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
 ```
not starting up since update to 15.1. 

```
[13:35:12] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /config/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[13:35:13] INFO: Service AppDaemon exited with code 1 (by signal 0)
```

secrets file is avalable, according to vscode
![image](https://github.com/hassio-addons/addon-appdaemon/assets/842121/33006531-181c-43e6-9fb1-27929d1f3315)

Also, the appdeamon folder has been cleaned, which is... unexpected.
![image](https://github.com/hassio-addons/addon-appdaemon/assets/842121/449800b8-10a2-46cc-bf8e-53e5e0341cc3)

## Expected behavior

Appdaemon starts without errors

## Actual behavior

see problem description

## Steps to reproduce

upgrade to 15.1. from 14.x

## Proposed changes

none

**Comment by frenck** [comment] 2023-11-15 12:51
duplicate of #287

**Closed as completed by frenck** 2023-11-15 12:51 UTC
