### ISSUE TITLE
Updates are broken going from 0.14.0 to 0.15.2

### ISSUE THREAD

**Issue by deviantintegral** [hassio-addons/app-appdaemon#299] opened 2023-11-16 17:26 UTC
# Problem/Motivation

I get the following error when updating. As I'm using zfs, I used its rollback to recreate. There isn't any chance that the restore back to 0.14.0 was messed up.

I know https://github.com/hassio-addons/addon-appdaemon/issues/287 is very similar, but that issue has very much gone down the path of discussing the config change itself, so I figured it made more sense to file an issue that the migration is still broken.

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.15.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.1  (amd64 / qemux86-64)
 Home Assistant Core: 2023.11.2
 Home Assistant Supervisor: 2023.11.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[12:21:13] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
ERROR Error loading secrets file: /config/secrets.yaml
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[12:21:16] INFO: Service AppDaemon exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service appdaemon: stopping
s6-rc: info: service appdaemon successfully stopped
s6-rc: info: service init-appdaemon: stopping
s6-rc: info: service init-appdaemon successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

## Expected behavior

appdaemon starts :D

## Actual behavior

It doesn't!

## Steps to reproduce

Run update from 0.14.0 to 0.15.2.

## Proposed changes

I think the migration should either update the secrets line, or at least error out with clear steps to fix instead of a backtrace.

**Comment by andarotajo** [comment] 2023-11-16 17:32
As far as I know, the migration does not involve manipulating the user's YAML files (be it configuration or app related). The release notes should give you information on how to fix it: https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.2 (changing the `/config` to `/homeassistant`)

**Comment by deviantintegral** [comment] 2023-11-16 17:59
For some reason those notes aren't showing up in Supervisor:

<img width="1071" alt="image" src="https://github.com/hassio-addons/addon-appdaemon/assets/255023/ea653916-df80-4acc-81f0-3f95a71c838f">

<img width="633" alt="image" src="https://github.com/hassio-addons/addon-appdaemon/assets/255023/9bbe42d5-87f4-460e-bc68-81aa96478a4f">

**Comment by joBr99** [comment] 2023-11-16 18:05
@deviantintegral 

Does the new folder exist?

I tried this with my HA Test install 2 times upgrading from 14 to 15.2 and the config is still completely gone. (Used zfs to rollback as well)

I will prepare a video after dinner.

**Comment by andarotajo** [comment] 2023-11-16 18:20
> For some reason those notes aren't showing up in Supervisor:
> <img alt="image" width="1071" src="https://user-images.githubusercontent.com/255023/283550295-ea653916-df80-4acc-81f0-3f95a71c838f.png"> <img alt="image" width="633" src="https://user-images.githubusercontent.com/255023/283550432-9bbe42d5-87f4-460e-bc68-81aa96478a4f.png">

I had that too. I think the other part was initially just in the `0.15.1` version but edited in afterwards for the `0.15.2`. Don't know, if it's incomplete for everyone or just buggy for some, though.

**Comment by joBr99** [comment] 2023-11-16 18:31
https://github.com/hassio-addons/addon-appdaemon/assets/29555657/9f28438e-a5c1-4085-ba84-0aa49d03858c

Upgrade from 14.0 to 15.2, no /addon_configs folder after the upgrade. Tried this 2 times. (Restored my entire test VM from backup/snapshots)

The old previously existing appdaemon folder is cleared.

**Comment by andarotajo** [comment] 2023-11-16 18:44
@joBr99 Not sure, if I can help with this one. It might require a newer version for either HA Core, HA OS or the Supervisor, seeing that you are missing some. The addition of `addon_configs` did not originate from any add-on but from HA itself, as far as I know (see https://developers.home-assistant.io/blog/2023/11/06/public-addon-config)

**Comment by joBr99** [comment] 2023-11-16 19:17
Tried a 3rd time with current HA OS etc. and the migration worked this time.

**Comment by ClemensSchartmueller** [comment] 2023-11-16 20:06
Hey, I had the same issue and read your comments and the changelog. Maybe it would be good to add to the changelog that this is actually a breaking change (?) and also where the appdaemon.yaml is located (in `/addon_configs/xxx_appdaemon/`)

**Comment by wernerhp** [comment] 2023-11-16 21:45
Can fix this by creating a symbolic link to the new `/root/addon_configs/a0d7b954_appdaemon/` older in `/root/config/appdaemon` like so...

```
ln -s /root/addon_configs/a0d7b954_appdaemon/ /root/config/appdaemon
```

See also the [release notes](https://github.com/hassio-addons/addon-appdaemon/releases/tag/v0.15.2)

You may also need to edit `/root/addon_configs/a0d7b954_appdaemon/appdaemon.yaml` and update
```
secrets: /config/secrets.yaml
```
to
```
secrets: /homeassistant/secrets.yaml
```

**Comment by frenck** [comment] 2023-11-17 11:57
Duplicate of #287 

Please be sure to update the paths as listed in the release notes.

../Frenck

**Closed as not planned by frenck** 2023-11-17 11:57 UTC
