### ISSUE TITLE
Latest release

### ISSUE THREAD

**Issue by Jurgenn22** [hassio-addons/app-appdaemon#147] opened 2021-08-23 19:41 UTC
# Problem/Motivation

> Latest release broke dashboard vieuw on Ipad with safari and chrome browser, showing only empty widgets.

## Expected behavior

> That dashboard on the ipad on safari and chrome works as before.

## Actual behavior

> dashboard vieuw on Ipad with safari and chrome browser, showing only empty widgets. When a snapshot from the addon is restored with the previous release, everything works as before.

## Steps to reproduce

> 

## Proposed changes

> 
>

**Comment by sinclairpaul** [comment] 2021-08-23 21:28
Likely duplicate of #146

**Closed as completed** 2021-08-23 21:32 UTC
