### ISSUE TITLE
Socket.io can't be used in version 0.4.0

### ISSUE THREAD

**Issue by skannea** [hassio-addons/app-appdaemon#64] opened 2021-01-27 20:57 UTC
[This issue ](https://github.com/AppDaemon/appdaemon/issues/1140#issue) was moved here.
# Problem/Motivation
After upgrading AD add-on from 0.3.2 to 0.4.0 all numbers and icons are missing in all my HAdashboards.
The reason seems to be that it is no longer possible to use the socket.io option in appdaemon.yaml:

```
http: 
  transport: socketio

```

The reason I am not using websockets (which is default) is that I am using iOS clients ( iPad and iPhone ) for remote access to the HAdashboards.
In combination with Nginx ( Nginx Proxy Server add-on for HA ) set up with user/password authorization, websockets can't be used.

## Actual behavior

This was logged when starting the AD add-on:

```
...
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.```
Add-on version: 0.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.15  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:49:30] INFO: Starting AppDaemon...
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
...

```
This was logged (for each API call, I guess) by the client ( Chrome or Edge browser on Windows )

```
VM2793:1 GET http://192.168.0.111:5050/socket.io/?EIO=3&transport=polling&t=NT0Fjlu 400 (Bad Request)
(anonymous) @ VM2793:1
window.XMLHttpRequest.send @ main.js?attr=-MhlPDGlhq6D7Mdgw7l04b9nZsnpdwK9bObFSmZ5ne6Tr-RmiigE6S7SsUwo2FJbVHpqB-HDpo50BzkOn7AxOA:3024
i.create @ socket.io.js:7
i @ socket.io.js:7
o.request @ socket.io.js:7
o.doPoll @ socket.io.js:7
r.poll @ socket.io.js:7
r.doOpen @ socket.io.js:7
r.open @ socket.io.js:7
r.open @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r.open.r.connect @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
SocketIOStream @ stream.js:288
Stream @ stream.js:214
DashStream @ dashboard.js:137
(anonymous) @ carheat_init.js:123
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3

```

I found these log snippets. I guess it is before and after update.

```
2021-01-26 19:23:40.060059 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2021-01-26 19:23:40.061515 INFO AppDaemon: Python version is 3.8.5
...
021-01-26 19:32:37.585150 INFO AppDaemon: AppDaemon is stopped.
2021-01-26 19:33:37.566203 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2021-01-26 19:33:37.566714 INFO AppDaemon: Python version is 3.8.7

```

## Steps to reproduce

```
http:
  transport: socketio
```

**Comment by frenck** [comment] 2021-01-27 21:07
Actually, it is an appdaemon issue, will comment on the original issue and close this one up here.

**Comment by frenck** [comment] 2021-01-28 00:04
Re-opening issue, as on the AppDaemon end, they think it is because of the Python upgrade 🤦 

I can override AppDaemon behavior from the add-on, so I will make the add-on patch up AppDaemon to deal with their issue.

That said, it is currently 1am in my timezone, so will catch up with some sleep first.

**Comment by frenck** [comment] 2021-01-28 10:21
Started working on this.

**Comment by frenck** [comment] 2021-01-28 10:27
Reproduced the issue:

```
2021-01-28 10:27:04.009369 INFO AppDaemon: function [get_dashboard] finished in 61 ms
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
```

**Comment by frenck** [comment] 2021-01-28 10:32
Patched AppDaemon itself:

```
2021-01-28 10:29:56.427466 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2021-01-28 10:29:56.427567 INFO AppDaemon: Python version is 3.8.7
...
2021-01-28 10:29:56.446143 INFO AppDaemon: Initializing HTTP
2021-01-28 10:29:56.446295 INFO AppDaemon: Using 'socketio' for event stream
2021-01-28 10:29:56.448155 INFO AppDaemon: Starting API
2021-01-28 10:29:56.449854 INFO AppDaemon: Starting Admin Interface
...
2021-01-28 10:29:58.519554 INFO hello_world: Hello from AppDaemon
2021-01-28 10:29:58.520012 INFO hello_world: You are now ready to run Apps!
2021-01-28 10:29:58.520776 INFO AppDaemon: App initialization complete
2021-01-28 10:30:02.418785 INFO AppDaemon: New client Admin Client connected
```

![image](https://user-images.githubusercontent.com/195327/106125404-6be53100-615c-11eb-8fc4-5b0d175736a7.png)


Success 💪 


Will perform the regular maintenance as well, and push out a new version today.

**Comment by frenck** [comment] 2021-01-28 10:57
For full completeness/documentation in this issue:

At this point, the Socket.io Javascript library included en vendors here in AppDaemon dates from 2018. It's version 2.1.1.

See:

https://github.com/AppDaemon/appdaemon/blob/ac6de7dce88f32be32f1c64c2c368d279b019dff/appdaemon/assets/javascript/socket.io.js#L2

Furthermore, AppDaemon pins Python package: `python-socketio==4.4.0` and dates from 2019.

See:

https://github.com/AppDaemon/appdaemon/blob/e7e0976fb46a5e4e0e3b492d8022f4154215c924/requirements.txt#L15

So far so good. Python packages `python-socketio==4.4.0`, depends on `python-engineio>=3.9.0`. Which means any version above 3.9.0.

See:

https://github.com/miguelgrinberg/python-socketio/blob/610ee2cf1fe615b0c8ef229417dcd8e1ddf877c1/setup.py#L33

The latest version of `python-engineio` is 4.0.0, which will be installed on a fresh environment, as it matches the >=3.9.0 condition listed above.

See:

https://github.com/miguelgrinberg/python-engineio/releases

However, that version of engineio isn't compatible with either of the clients listed above.

If you are looking for more information on this, you can read this really long thread I just found on the same subject.

https://github.com/miguelgrinberg/python-socketio/issues/578

Screenshot of the compatibility table, showing engineio not being compatible with the socketio libraries used by AppDaemon:

![image](https://user-images.githubusercontent.com/195327/106128915-190d7880-6160-11eb-9374-b97c2661c7c4.png)

Conclusion; it isn't a Python version. It is a pinning issue.

**Closed as completed** 2021-01-28 11:26 UTC
Labels: priority-medium

**Comment by frenck** [comment] 2021-01-28 12:22
![image](https://user-images.githubusercontent.com/195327/106137857-9b4f6a00-616b-11eb-9b99-7a1ec16d0dc1.png)

@skannea ☝️ 

The update is available. If it doesn't show up yet on your system: Supervisor panel -> Add-on Store -> Three dotted menu in the top right -> Reload.

After that, the upgrade should be available.

Sorry, you got stuck with this bug and the upstream discussion. Hopefully, this eases the pain a bit 👍

**Comment by skannea** [comment] 2021-01-28 16:18
@frenck , very impressive response on my issue!
As far as I can see it works fine. However, I got a lot of 
`2021-01-28 16:58:47.375603 WARNING AppDaemon: Dashboard 'stream' not found
`
I tried to find and stop all running clients and I guess that fixed it.
