### ISSUE TITLE
Config gone from 'config' as announced, not working in new folder, and can't be restored with 'partial restore'

### ISSUE THREAD

**Issue by fribse** [hassio-addons/app-appdaemon#298] opened 2023-11-16 06:40 UTC
# Problem/Motivation

My ControllerX config is gone with the appdaemon config

## Expected behavior

Well, I would hope that all my button automations would work through ControllerX

## Actual behavior

No appdaemon apps found

## Steps to reproduce

Upgraded the normal way

## Proposed changes

Keep the config, and make it retreivable through 'partial restore'

**Comment by PPP01** [comment] 2023-11-16 07:35
Maybe the same error here. The whole appdaemon folder is empty after the update. It's totally clean, an empty folder.

**Comment by fribse** [comment] 2023-11-16 07:41
Well it's supposed to be moved to addon_configs, but that didn't work, and partial restore from a backup doesn't bring the config back either :-(

**Comment by PPP01** [comment] 2023-11-16 07:44
Yes, my addon_config folder is empty, too. So all my apps and settings are gone for the moment. It seems that I have to do a complete restore.

**Comment by frenck** [comment] 2023-11-16 07:48
Duplicate of #287

**Closed as completed by frenck** 2023-11-16 07:48 UTC
