### ISSUE TITLE
my appdaemon won't keep running I start it then chack back later and its not running

### ISSUE THREAD

**Issue by morrydavis** [hassio-addons/app-appdaemon#304] opened 2023-11-18 00:54 UTC
# Problem/Motivation

> appdaemon keeps stopping I think it is affecting my schedy_heating,yaml

## Expected behavior

> dah! exprct it to keep running

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by NicoLeOca** [comment] 2023-11-18 07:08
you should check this issue:
https://github.com/hassio-addons/addon-appdaemon/issues/303

**Comment by bartgabriels** [comment] 2023-11-18 08:35
> you should check this issue: #303

This fixes indeed the issue.
 1/ Install terminal if it's not yet installed on your system
 2/ `cd addon_configs` 
3/ `ls` to look for your xxxxxx_appdeamon folder
4/ `cd xxxxxx_appdeamon`
5/ `vi appdeamon.yaml`

and then edit the line saying `secrets: /config/secrets.yaml` to `secrets: /homeassistant/secrets.yaml`

Some tricks in VI:
1/ first use 'i' to get into insert mode
2/ replace the config with homeassistant
3/ Press ESC
4/ type :wq to save and exit

**Comment by morrydavis** [comment] 2023-11-20 18:18
Thanks got it working would like to cleanup what directories and files can be deleted

**Comment by frenck** [comment] 2023-11-28 19:28
Symlink sounds like a bad approach, but if that works for you 🤷 
Would not recommend. Instead, adjust the configuration correctly.

Otherwise duplicate of #287

../Frenck

**Closed as not planned by frenck** 2023-11-28 19:28 UTC
