### ISSUE TITLE
Appdeamon stopped working and erased appdeamon folder from 14.0 to 15.2

### ISSUE THREAD

**Issue by PolestarWx** [hassio-addons/app-appdaemon#297] opened 2023-11-15 19:23 UTC
# Problem/Motivation

Appdeamon stopped working and erased appdeamon folder from 14.0 to 15.2,

I need help to know if it is possible to recover my appdeamon app

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment] 2023-11-15 19:26
Duplicate of #287

**Closed as completed by frenck** 2023-11-15 19:26 UTC
